=== phantomcyber/dev-cicd-tools/pre-commit/app_tests/app_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
      "appid": {
        "type": "string",
        "format": "uuid"
      },
      "name": {
        "type": "string"
      },
      "description": {
        "type": "string",
        "pattern": "^(|[^a-z][\\s\\S]*)$"
      },
      "publisher": {
        "type": "string"
      },
      "package_name": {
        "type": "string",
        "pattern": "^phantom_.+$"
      },
      "type": {
        "type": "string",
        "enum": [
          "devops",
          "email",
          "endpoint",
          "identity management",
          "information",
          "network device",
          "network security",
          "reputation",
          "sandbox",
          "siem",
          "ticketing",
          "firewall",
          "virtualization",
          "forensic",
          "investigative",
          "threat intel",
          "generic",
          "directory service",
          "internal",
          "vulnerability scanner"
        ]
      },
      "license": {
        "type": "string"
      },
      "main_module": {
        "type": "string",
        "pattern": "\\.py$"
      },
      "app_version": {
        "type": "string",
        "pattern": "^[0-9]+[.][0-9]+[.][0-9]+$"
      },
      "utctime_updated": {
        "type": "string",
        "format": "date-time"
      },
      "product_vendor": {
        "type": "string"
      },
      "product_name": {
        "type": "string"
      },
      "product_version_regex": {
        "type": "string"
      },
      "min_phantom_version": {
        "type": "string",
        "pattern": "^(\\d+\\.){2,3}\\d+$"
      },
      "fips_compliant": {
        "type": "boolean"
      },
      "python_version": {
        "oneOf": [
          {
            "type": "string",
            "pattern": "^3(\\.\\d+)?(,\\s*3(\\.\\d+)?)*$"
          },
          {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^3(\\.\\d+)?$"
            }
          }
        ]
      },
      "latest_tested_versions": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "logo": {
        "type": "string"
      },
      "logo_dark": {
        "type": "string"
      },
      "app_wizard_version": {
        "type": "string"
      },
      "rest_handler": {
        "type": "string"
      },
      "consolidate_widgets": {
        "type": "boolean"
      },
      "qa_metadata": {
        "type": "object"
      },
      "contributors": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": {
            "name": {
              "type": "string",
              "required": [
                "name"
              ]
            }
          }
        }
      },
      "configuration": {
        "type": "object",
        "additionalProperties": {
          "type": "object",
          "properties": {
            "description": {
              "type": "string",
              "pattern": "^(|[^a-z][\\s\\S]*)$"
            },
            "data_type": {
              "type": "string",
              "enum": [
                "string",
                "numeric",
                "boolean",
                "password",
                "ph",
                "timezone",
                "file",
                "object",
                "array"
              ]
            },
            "required": {
              "type": "boolean"
            },
            "order": {
              "type": "integer"
            },
            "default": {},
            "value_list": {
              "type": "array",
              "items": {}
            },
            "contains": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "data_type"
          ],
          "if": {
            "properties": { "data_type": { "const": "password" } }
          },
          "then": {
            "properties": {
              "default": { "const": "" },
              "value_list": { "maxItems": 0 }
            }
          }
        }
      },
      "actions": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "action": {
              "type": "string",
              "pattern": "[a-z 0-9]+"
            },
            "description": {
              "type": "string",
              "pattern": "^(|[^a-z][\\s\\S]*[^\\.])$"
            },
            "verbose": {
              "type": "string",
              "pattern": "^(|[^a-z][\\s\\S]*)$"
            },
            "type": {
              "type": "string",
              "enum": [
                "generic",
                "investigate",
                "contain",
                "correct",
                "test",
                "ingest"
              ]
            },
            "identifier": {
              "type": "string"
            },
            "read_only": {
              "type": "boolean"
            },
            "lock": {
              "type": "object",
              "properties": {
                "enabled": {
                  "type": "boolean"
                }
              }
            },
            "parameters": {
              "type": "object",
              "additionalProperties": {
                "type": "object",
                "properties": {
                  "description": {
                    "type": "string",
                    "pattern": "^(|[^a-z][\\s\\S]*)$"
                  },
                  "data_type": {
                    "type": "string"
                  },
                  "required": {
                    "type": "boolean"
                  },
                  "order": {
                    "type": "integer"
                  },
                  "primary": {
                    "type": "boolean"
                  },
                  "default": {},
                  "value_list": {
                    "type": "array",
                    "items": {}
                  },
                  "contains": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "allow_list": {
                    "type": "boolean"
                  }
                },
                "required": [
                  "data_type"
                ]
              }
            },
            "output": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "data_path": {
                    "type": "string",
                    "not": {
                      "pattern": "^action_result\\.data\\.[^.]+\\.data\\.[^.]+$"
                    }
                  },
                  "data_type": {
                    "type": "string"
                  },
                  "example_values": {
                    "type": "array",
                    "items": {
                      "type": [
                        "string",
                        "boolean",
                        "number",
                        "array",
                        "object",
                        "null"
                      ]
                    }
                  },
                  "column_name": {
                    "type": "string"
                  },
                  "column_order": {
                    "oneOf": [
                      {
                        "type": "integer"
                      },
                      {
                        "type": "string",
                        "pattern": "^[0-9]+$"
                      }
                    ]
                  },
                  "contains": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "map_info": {
                    "type": "string"
                  }
                },
                "required": [
                  "data_path",
                  "data_type"
                ]
              }
            },
            "render": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string"
                },
                "width": {
                  "type": "number"
                },
                "height": {
                  "type": "number"
                },
                "title": {
                  "type": "string"
                },
                "menu_name": {
                  "type": "string"
                }
              }
            },
            "versions": {
              "type": "string"
            }
          },
          "required": [
            "action",
            "description",
            "type",
            "identifier",
            "read_only"
          ]
        }
      },
      "pip_dependencies": {
        "type": "object",
        "properties": {
          "pypi": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "module": {
                  "type": "string"
                }
              },
              "required": [
                "module"
              ]
            }
          },
          "wheel": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "module": {
                  "type": "string"
                },
                "input_file": {
                  "type": "string"
                }
              },
              "required": [
                "module",
                "input_file"
              ]
            }
          }
        }
      },
      "pip3_dependencies": {
        "type": "object",
        "properties": {
          "pypi": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "module": {
                  "type": "string"
                }
              },
              "required": [
                "module"
              ]
            }
          },
          "wheel": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "module": {
                  "type": "string"
                },
                "input_file": {
                  "type": "string"
                }
              },
              "required": [
                "module",
                "input_file"
              ]
            }
          }
        }
      },
      "pip39_dependencies": {
        "type": "object",
        "properties": {
          "pypi": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "module": {
                  "type": "string"
                }
              },
              "required": [
                "module"
              ]
            }
          },
          "wheel": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "module": {
                  "type": "string"
                },
                "input_file": {
                  "type": "string"
                }
              },
              "required": [
                "module",
                "input_file"
              ]
            }
          }
        }
      },
      "pip313_dependencies": {
        "type": "object",
        "properties": {
          "pypi": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "module": {
                  "type": "string"
                }
              },
              "required": [
                "module"
              ]
            }
          },
          "wheel": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "module": {
                  "type": "string"
                },
                "input_file": {
                  "type": "string"
                }
              },
              "required": [
                "module",
                "input_file"
              ]
            }
          }
        }
      }
    },
    "required": [
      "actions",
      "app_version",
      "appid",
      "configuration",
      "description",
      "license",
      "logo",
      "main_module",
      "min_phantom_version",
      "name",
      "package_name",
      "product_name",
      "product_vendor",
      "python_version",
      "product_version_regex",
      "publisher",
      "type"
    ],
    "if": {
      "properties": {
        "publisher": {
          "const": "Splunk"
        }
      }
    },
    "then": {
      "required": ["fips_compliant"]
    }
  }

=== phantomcyber/dev-cicd-tools/local_hooks/tests/data/static_tests/sdk_app_dir/sdk_app_manifest.json
{
    "appid": "501b54a8-4bad-4b65-ad7b-d6ac4e5e49c8",
    "name": "Static test",
    "description": "To test changes to CI/CD. using cisco secure firewalls actions",
    "type": "information",
    "product_vendor": "Splunk",
    "logo": "logo_cisco.svg",
    "logo_dark": "logo_cisco_dark.svg",
    "product_name": "Static tests",
    "python_version": "3",
    "latest_tested_versions": [
        "Cloud, October 30, 2024"
    ],
    "product_version_regex": ".*",
    "publisher": "Splunk",
    "license": "Copyright (c) 2025 Splunk Inc.",
    "app_version": "1.0.6",
    "utctime_updated": "2025-01-17T22:32:42.000000Z",
    "package_name": "phantom_static_tests",
    "main_module": "src.app:App",
    "min_phantom_version": "6.3.0",
    "app_wizard_version": "1.0.1",
    "configuration": {
        "api_key": {
            "description": "Api key for cloud delivered FMC",
            "data_type": "password",
            "order": 0
        }
    },
    "actions": [
        {
            "action": "test connectivity",
            "identifier": "test_connectivity",
            "description": "Validate the asset configuration for connectivity using supplied configuration",
            "type": "test",
            "read_only": true,
            "parameters": {},
            "output": [],
            "versions": "EQ(*)"
        }
   ]
}

=== phantomcyber/dev-cicd-tools/pre-commit/tests/data/static_tests/expected/statictests.json
{
    "appid": "501b54a8-4bad-4b65-ad7b-d6ac4e5e49c8",
    "name": "Static test",
    "description": "To test changes to CI/CD. using cisco secure firewalls actions",
    "type": "information",
    "product_vendor": "Splunk",
    "logo": "logo_cisco.svg",
    "logo_dark": "logo_cisco_dark.svg",
    "product_name": "Static tests",
    "python_version": "3",
    "latest_tested_versions": [
        "Cloud, October 30, 2024"
    ],
    "product_version_regex": ".*",
    "publisher": "Splunk",
    "license": "Copyright (c) 2025 Splunk Inc.",
    "app_version": "1.0.6",
    "utctime_updated": "2025-01-17T22:32:42.000000Z",
    "package_name": "phantom_static_tests",
    "main_module": "statictests_connector.py",
    "min_phantom_version": "6.2.0",
    "app_wizard_version": "1.0.1",
    "configuration": {
        "api_key": {
            "description": "Api key for cloud delivered FMC",
            "data_type": "password",
            "order": 0
        },
        "region": {
            "description": "Region your Cisco Security Cloud Control is deployed in",
            "data_type": "string",
            "value_list": [
                "US",
                "EU",
                "APJ",
                "AUS",
                "IN"
            ],
            "order": 1
        },
        "domain": {
            "description": "Domain for the FMC",
            "data_type": "string",
            "order": 2
        }
    },
    "actions": [
        {
            "action": "test connectivity",
            "identifier": "test_connectivity",
            "description": "Validate the asset configuration for connectivity using supplied configuration",
            "type": "test",
            "read_only": true,
            "parameters": {},
            "output": [],
            "versions": "EQ(*)"
        },
        {
            "action": "list network objects",
            "description": "List network object in FMC",
            "type": "investigate",
            "read_only": true,
            "identifier": "list_network_objects",
            "parameters": {
                "name": {
                    "description": "Network object name to filter results by",
                    "data_type": "string",
                    "order": 0
                },
                "type": {
                    "description": "Network object type to filter results by",
                    "data_type": "string",
                    "value_list": [
                        "Host",
                        "Network",
                        "Range",
                        "FQDN"
                    ],
                    "order": 1
                },
                "domain_name": {
                    "description": "Firepower Domain. If none is specified the default domain will be queried",
                    "data_type": "string",
                    "contains": [
                        "domain"
                    ],
                    "order": 2
                }
            },
            "output": [
                {
                    "data_path": "action_result.status",
                    "data_type": "string",
                    "example_values": [
                        "success",
                        "failed"
                    ]
                },
                {
                    "data_path": "summary.total_objects",
                    "data_type": "numeric"
                },
                {
                    "data_path": "summary.total_objects_successful",
                    "data_type": "numeric"
                },
                {
                    "data_path": "action_result.parameter.type",
                    "data_type": "string",
                    "example_values": [
                        "Network"
                    ]
                },
                {
                    "data_path": "action_result.parameter.domain_name",
                    "data_type": "string",
                    "contains": [
                        "domain"
                    ]
                },
                {
                    "data_path": "action_result.data.*.id",
                    "data_type": "string",
                    "column_order": 0,
                    "column_name": "Object Id"
                },
                {
                    "data_path": "action_result.data.*.name",
                    "data_type": "string",
                    "column_name": "Object Name",
                    "column_order": 1
                },
                {
                    "data_path": "action_result.data.*.type",
                    "data_type": "string",
                    "example_values": [
                        "Network"
                    ],
                    "column_name": "Object Type",
                    "column_order": 2
                },
                {
                    "data_path": "action_result.data.*.links.self",
                    "data_type": "string"
                },
                {
                    "data_path": "action_result.data.*.links.parent",
                    "data_type": "string"
                },
                {
                    "data_path": "action_result.parameter.name",
                    "data_type": "string"
                },
                {
                    "data_path": "action_result.message",
                    "data_type": "string"
                }
            ],
            "render": {
                "title": "Network Objects",
                "type": "table"
            },
            "versions": "EQ(*)"
        }
    ]
}
